<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="stylesheet" href="/css/style.css">
    <script src="https://kit.fontawesome.com/a29066c225.js" crossorigin="anonymous"></script>
    <title>Служба подбора персонала King</title>
</head>
<body>
    <div class="navbar">
        <div class="center links">
            <div class="navbar-link"><i class="fa-solid fa-person"></i> Сотрудники</div>
            <div class="navbar-link" style="margin-left: 1rem;"><i class="fa-solid fa-building"></i> Департаменты </div>
            <div class="navbar-link" style="margin-left: auto;"><i class="fa-solid fa-language"></i> RU</div>
        </div>
    </div>
    <div class="content">
        <div class="center">
            <?= $this->content ?>
        </div>
    </div>
    <div class="footer">
        <div class="center">
            <p>Служба подбора персонала Кинга</p>
            <p style="margin-top: 1rem;">Язык: Русский | Английский</p>
        </div>

    </div>
</body>
</html>